# Render configuration for Ayush Terminology Portal Backend
services:
  - type: web
    name: ayush-terminology-backend
    runtime: node
    region: oregon # Choose your preferred region
    branch: main # Replace with your branch name
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false # This will be set in the Render dashboard
      - key: FRONTEND_URL
        sync: false # This will be set in the Render dashboard with your Vercel URL
      - key: API_VERSION
        value: v1
    healthCheckPath: /health
    autoDeploy: true